apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080         # Service port
      targetPort: nginx-port     # Pod container port
  type: LoadBalancer

